version: '3.9'

secrets:
  certificate-issuance-secret-id:
    external: true

services:
  nginx:
    image: docker.io/thefnordling/homelab-nginx:1.0.15
    environment:
      - VAULT_ADDR=http://swarm1.home.arpa:8200
      - ROLE_ID=74548022-db81-5c30-681c-3b5f441c9af4
      - SECRET_ID_FILE=/run/secrets/secret-id
    secrets:
      - source: certificate-issuance-secret-id
        target: /run/secrets/secret-id
    ports:
      - 80:80
      - 443:443
    volumes:
      - default.conf:/etc/nginx/conf.d/default.conf